/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeMX
 * @brief     Minimal System calls file
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib or Picolibc libc-manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2020-2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <sys/stat.h>
#include <fcntl.h>
#include <stdarg.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#include <time.h>
#include <sys/time.h>
#include <sys/times.h>

#include "lfs_port.h"


/* Variables */
extern int __io_putchar(int ch) __attribute__((weak));
extern int __io_getchar(void) __attribute__((weak));


char *__env[1] = { 0 };
char **environ = __env;

#ifndef O_ACCMODE
#define O_ACCMODE (O_RDONLY | O_WRONLY | O_RDWR)
#endif

#define SYS_FILE_FD_BASE 3
#define SYS_FILE_FD_MAX  8

typedef struct
{
  lfs_t *fs;
  lfs_file_t file;
  int in_use;
} sys_file_fd_t;

static sys_file_fd_t g_file_fds[SYS_FILE_FD_MAX];

static void set_errno_from_lfs(int rc)
{
  switch (rc)
  {
  case LFS_ERR_NOENT:
    errno = ENOENT;
    break;
  case LFS_ERR_NOTDIR:
    errno = ENOTDIR;
    break;
  case LFS_ERR_EXIST:
    errno = EEXIST;
    break;
  case LFS_ERR_NOMEM:
    errno = ENOMEM;
    break;
  case LFS_ERR_IO:
    errno = EIO;
    break;
  case LFS_ERR_INVAL:
    errno = EINVAL;
    break;
  case LFS_ERR_BADF:
    errno = EBADF;
    break;
  case LFS_ERR_ISDIR:
    errno = EISDIR;
    break;
  case LFS_ERR_NAMETOOLONG:
    errno = ENAMETOOLONG;
    break;
  case LFS_ERR_FBIG:
    errno = EFBIG;
    break;
  case LFS_ERR_NOSPC:
    errno = ENOSPC;
    break;
  default:
    errno = EIO;
    break;
  }
}

static lfs_t *get_lfs_or_init(void)
{
  lfs_t *lfs = lfs_port_fs();
  int rc;

  if (lfs != NULL)
  {
    return lfs;
  }

  rc = lfs_port_init();
  if (rc < 0)
  {
    set_errno_from_lfs(rc);
    return NULL;
  }

  lfs = lfs_port_fs();
  if (lfs == NULL)
  {
    errno = EIO;
  }

  return lfs;
}

static int map_open_flags(int flags)
{
  int lfs_flags = 0;

  switch (flags & O_ACCMODE)
  {
  case O_RDONLY:
    lfs_flags |= LFS_O_RDONLY;
    break;
  case O_WRONLY:
    lfs_flags |= LFS_O_WRONLY;
    break;
  case O_RDWR:
    lfs_flags |= LFS_O_RDWR;
    break;
  default:
    errno = EINVAL;
    return -1;
  }

  if ((flags & O_CREAT) != 0)
  {
    lfs_flags |= LFS_O_CREAT;
  }
  if ((flags & O_EXCL) != 0)
  {
    lfs_flags |= LFS_O_EXCL;
  }
  if ((flags & O_TRUNC) != 0)
  {
    lfs_flags |= LFS_O_TRUNC;
  }
  if ((flags & O_APPEND) != 0)
  {
    lfs_flags |= LFS_O_APPEND;
  }

  return lfs_flags;
}

static int alloc_file_fd(void)
{
  int idx;

  for (idx = 0; idx < SYS_FILE_FD_MAX; idx++)
  {
    if (!g_file_fds[idx].in_use)
    {
      g_file_fds[idx].in_use = 1;
      g_file_fds[idx].fs = NULL;
      memset(&g_file_fds[idx].file, 0, sizeof(g_file_fds[idx].file));
      return SYS_FILE_FD_BASE + idx;
    }
  }

  errno = EMFILE;
  return -1;
}

static sys_file_fd_t *get_file_fd(int fd)
{
  int idx = fd - SYS_FILE_FD_BASE;

  if ((fd < SYS_FILE_FD_BASE) || (idx < 0) || (idx >= SYS_FILE_FD_MAX))
  {
    return NULL;
  }

  if (!g_file_fds[idx].in_use)
  {
    return NULL;
  }

  return &g_file_fds[idx];
}


/* Functions */
void initialise_monitor_handles()
{
}

int _getpid(void)
{
  return 1;
}

int _kill(int pid, int sig)
{
  (void)pid;
  (void)sig;
  errno = EINVAL;
  return -1;
}

void _exit (int status)
{
  _kill(status, -1);
  while (1) {}    /* Make sure we hang here */
}

__attribute__((weak)) int _read(int file, char *ptr, int len)
{
  int DataIdx;
  sys_file_fd_t *ctx;
  lfs_ssize_t rc;

  if ((ptr == NULL) || (len < 0))
  {
    errno = EINVAL;
    return -1;
  }

  if (file < SYS_FILE_FD_BASE)
  {
    for (DataIdx = 0; DataIdx < len; DataIdx++)
    {
      *ptr++ = __io_getchar();
    }

    return len;
  }

  ctx = get_file_fd(file);
  if (ctx == NULL)
  {
    errno = EBADF;
    return -1;
  }

  if (ctx->fs == NULL)
  {
    errno = EIO;
    return -1;
  }

  rc = lfs_file_read(ctx->fs, &ctx->file, ptr, (lfs_size_t)len);
  if (rc < 0)
  {
    set_errno_from_lfs((int)rc);
    return -1;
  }

  DataIdx = (int)rc;
  return DataIdx;
}

__attribute__((weak)) int _write(int file, char *ptr, int len)
{
  int DataIdx;
  sys_file_fd_t *ctx;
  lfs_ssize_t rc;

  if ((ptr == NULL) || (len < 0))
  {
    errno = EINVAL;
    return -1;
  }

  if (file < SYS_FILE_FD_BASE)
  {
    for (DataIdx = 0; DataIdx < len; DataIdx++)
    {
      __io_putchar(*ptr++);
    }
    return len;
  }

  ctx = get_file_fd(file);
  if (ctx == NULL)
  {
    errno = EBADF;
    return -1;
  }

  if (ctx->fs == NULL)
  {
    errno = EIO;
    return -1;
  }

  rc = lfs_file_write(ctx->fs, &ctx->file, ptr, (lfs_size_t)len);
  if (rc < 0)
  {
    set_errno_from_lfs((int)rc);
    return -1;
  }

  DataIdx = (int)rc;
  return DataIdx;
}

int _close(int file)
{
  sys_file_fd_t *ctx;
  int rc;

  if (file < SYS_FILE_FD_BASE)
  {
    return 0;
  }

  ctx = get_file_fd(file);
  if (ctx == NULL)
  {
    errno = EBADF;
    return -1;
  }

  rc = lfs_file_close(ctx->fs, &ctx->file);
  ctx->in_use = 0;
  ctx->fs = NULL;
  memset(&ctx->file, 0, sizeof(ctx->file));

  if (rc < 0)
  {
    set_errno_from_lfs(rc);
    return -1;
  }

  return 0;
}


int _fstat(int file, struct stat *st)
{
  sys_file_fd_t *ctx;
  lfs_soff_t size;

  if (st == NULL)
  {
    errno = EINVAL;
    return -1;
  }

  if (file < SYS_FILE_FD_BASE)
  {
    st->st_mode = S_IFCHR;
    st->st_size = 0;
    return 0;
  }

  ctx = get_file_fd(file);
  if (ctx == NULL)
  {
    errno = EBADF;
    return -1;
  }

  size = lfs_file_size(ctx->fs, &ctx->file);
  if (size < 0)
  {
    set_errno_from_lfs((int)size);
    return -1;
  }

  st->st_mode = S_IFREG;
  st->st_size = (off_t)size;
  return 0;
}

int _isatty(int file)
{
  return (file < SYS_FILE_FD_BASE) ? 1 : 0;
}

int _lseek(int file, int ptr, int dir)
{
  sys_file_fd_t *ctx;
  lfs_soff_t rc;

  if (file < SYS_FILE_FD_BASE)
  {
    return 0;
  }

  ctx = get_file_fd(file);
  if (ctx == NULL)
  {
    errno = EBADF;
    return -1;
  }

  switch (dir)
  {
  case SEEK_SET:
    rc = lfs_file_seek(ctx->fs, &ctx->file, (lfs_soff_t)ptr, LFS_SEEK_SET);
    break;
  case SEEK_CUR:
    rc = lfs_file_seek(ctx->fs, &ctx->file, (lfs_soff_t)ptr, LFS_SEEK_CUR);
    break;
  case SEEK_END:
    rc = lfs_file_seek(ctx->fs, &ctx->file, (lfs_soff_t)ptr, LFS_SEEK_END);
    break;
  default:
    errno = EINVAL;
    return -1;
  }

  if (rc < 0)
  {
    set_errno_from_lfs((int)rc);
    return -1;
  }

  return (int)rc;
}

int _open(char *path, int flags, ...)
{
  lfs_t *lfs;
  sys_file_fd_t *ctx;
  int fd;
  int lfs_flags;

  if (path == NULL)
  {
    errno = EINVAL;
    return -1;
  }

  if ((flags & O_CREAT) != 0)
  {
    va_list ap;

    va_start(ap, flags);
    (void)va_arg(ap, int);
    va_end(ap);
  }

  lfs_flags = map_open_flags(flags);
  if (lfs_flags < 0)
  {
    return -1;
  }

  lfs = get_lfs_or_init();
  if (lfs == NULL)
  {
    return -1;
  }

  fd = alloc_file_fd();
  if (fd < 0)
  {
    return -1;
  }

  ctx = get_file_fd(fd);
  if (ctx == NULL)
  {
    errno = EBADF;
    return -1;
  }

  ctx->fs = lfs;
  {
    int rc = lfs_file_open(lfs, &ctx->file, path, lfs_flags);

    if (rc < 0)
    {
      ctx->in_use = 0;
      ctx->fs = NULL;
      memset(&ctx->file, 0, sizeof(ctx->file));
      set_errno_from_lfs(rc);
      return -1;
    }
  }

  return fd;
}

int _wait(int *status)
{
  (void)status;
  errno = ECHILD;
  return -1;
}

int _unlink(char *name)
{
  lfs_t *lfs;
  int rc;

  if (name == NULL)
  {
    errno = EINVAL;
    return -1;
  }

  lfs = get_lfs_or_init();
  if (lfs == NULL)
  {
    return -1;
  }

  rc = lfs_remove(lfs, name);
  if (rc < 0)
  {
    set_errno_from_lfs(rc);
    return -1;
  }

  return 0;
}

clock_t _times(struct tms *buf)
{
  (void)buf;
  return -1;
}

int _rename(const char *oldpath, const char *newpath)
{
  lfs_t *lfs;
  int rc;

  if ((oldpath == NULL) || (newpath == NULL))
  {
    errno = EINVAL;
    return -1;
  }

  lfs = get_lfs_or_init();
  if (lfs == NULL)
  {
    return -1;
  }

  rc = lfs_rename(lfs, oldpath, newpath);
  if (rc < 0)
  {
    set_errno_from_lfs(rc);
    return -1;
  }

  return 0;
}

int rename(const char *oldpath, const char *newpath)
{
  return _rename(oldpath, newpath);
}

int _stat(const char *file, struct stat *st)
{
  lfs_t *lfs;
  struct lfs_info info;
  int rc;

  if ((file == NULL) || (st == NULL))
  {
    errno = EINVAL;
    return -1;
  }

  lfs = lfs_port_fs();
  if (lfs != NULL)
  {
    rc = lfs_stat(lfs, file, &info);
    if (rc == 0)
    {
      st->st_mode = (info.type == LFS_TYPE_DIR) ? S_IFDIR : S_IFREG;
      st->st_size = (off_t)info.size;
      return 0;
    }

    switch (rc)
    {
    case LFS_ERR_NOENT:
      errno = ENOENT;
      break;
    case LFS_ERR_NOTDIR:
      errno = ENOTDIR;
      break;
    case LFS_ERR_EXIST:
      errno = EEXIST;
      break;
    case LFS_ERR_NOMEM:
      errno = ENOMEM;
      break;
    case LFS_ERR_IO:
      errno = EIO;
      break;
    case LFS_ERR_INVAL:
      errno = EINVAL;
      break;
    case LFS_ERR_BADF:
      errno = EBADF;
      break;
    case LFS_ERR_ISDIR:
      errno = EISDIR;
      break;
    case LFS_ERR_NAMETOOLONG:
      errno = ENAMETOOLONG;
      break;
    case LFS_ERR_FBIG:
      errno = EFBIG;
      break;
    case LFS_ERR_NOSPC:
      errno = ENOSPC;
      break;
    default:
      errno = EIO;
      break;
    }
    return -1;
  }

  /* Fallback before littlefs is mounted: keep console-like behavior. */
  st->st_mode = S_IFCHR;
  st->st_size = 0;
  return 0;
}

#if !defined(__PICOLIBC__)
/*
 * Use GCC alias attribute so that stat/fstat share the same address
 * as _stat/_fstat.  GDB can then break on either name and land directly
 * in the implementation, instead of stepping through a wrapper frame.
 */
int stat(const char *file, struct stat *st) __attribute__((alias("_stat")));
int fstat(int file, struct stat *st) __attribute__((alias("_fstat")));

int remove(const char *path)
{
  return _unlink((char *)path);
}
#endif

int _link(char *old, char *new)
{
  (void)old;
  (void)new;
  errno = EMLINK;
  return -1;
}

int _fork(void)
{
  errno = EAGAIN;
  return -1;
}

int _execve(char *name, char **argv, char **env)
{
  (void)name;
  (void)argv;
  (void)env;
  errno = ENOMEM;
  return -1;
}

// --- Picolibc Specific Section ---
#if defined(__PICOLIBC__)

/**
 * @brief Picolibc helper function to output a character to a FILE stream.
 *        This redirects the output to the low-level __io_putchar function.
 * @param c Character to write.
 * @param file FILE stream pointer (ignored).
 * @retval int The character written.
 */
static int starm_putc(char c, FILE *file)
{
	(void) file;
  __io_putchar(c);
	return c;
}

/**
 * @brief Picolibc helper function to input a character from a FILE stream.
 *        This redirects the input from the low-level __io_getchar function.
 * @param file FILE stream pointer (ignored).
 * @retval int The character read, cast to an unsigned char then int.
 */
static int starm_getc(FILE *file)
{
	unsigned char c;
	(void) file;
  c = __io_getchar();
	return c;
}

// Define and initialize the standard I/O streams for Picolibc.
// FDEV_SETUP_STREAM connects the starm_putc and starm_getc helper functions to a FILE structure.
// _FDEV_SETUP_RW indicates the stream is for reading and writing.
static FILE __stdio = FDEV_SETUP_STREAM(starm_putc,
					starm_getc,
					NULL,
					_FDEV_SETUP_RW);

// Assign the standard stream pointers (stdin, stdout, stderr) to the initialized stream.
// Picolibc uses these pointers for standard I/O operations (printf, scanf, etc.).
FILE *const stdin = &__stdio;
__strong_reference(stdin, stdout);
__strong_reference(stdin, stderr);

// Create strong aliases mapping standard C library function names (without underscore)
// to the implemented system call stubs (with underscore). Picolibc uses these
// standard names internally, so this linking is required.
__strong_reference(_read, read);
__strong_reference(_write, write);
__strong_reference(_times, times);
__strong_reference(_execve, execve);
__strong_reference(_fork, fork);
__strong_reference(_link, link);
__strong_reference(_unlink, unlink);
__strong_reference(_stat, stat);
__strong_reference(_wait, wait);
__strong_reference(_open, open);
__strong_reference(_close, close);
__strong_reference(_lseek, lseek);
__strong_reference(_isatty, isatty);
__strong_reference(_fstat, fstat);
__strong_reference(_exit, exit);
__strong_reference(_kill, kill);
__strong_reference(_getpid, getpid);

#endif //__PICOLIBC__
